#1030:add docker check in setup and close terminal after installation
devonfw/ide pull request #1036
Opened 2023-01-13 09:35 UTC by Ttring

- Instead of refreshing the environment variable, it closes the terminal after installation.

2023-01-17 15:59 UTC, hohwille requested changes
@Ttring thanks for your PR and efforts to improve devonfw-ide. 👍 
As some changes can not be merged as is, I would kindly like to ask how to proceed.
Will you have capacity to rework? Or should we incorporate some of your ideas and changes ourselves?

2023-01-17 15:59 UTC, hohwille commented on scripts/src/main/resources/scripts/command/docker
> +      if doIsDockerInstalled
actually this check should be done independent of `${DOCKER_EDITION}`.
If `docker` is already present, `doSetup` has nothing left to do.

2023-01-17 15:59 UTC, hohwille commented on scripts/src/main/resources/scripts/command/docker
> +          if [ "${1}" != "silent" ] && ! doIsQuiet
looks quite duplicated now...

2023-01-17 15:59 UTC, hohwille commented on scripts/src/main/resources/scripts/command/docker
> +        doRunCommand "${DEVON_DOWNLOAD_DIR}/docker-stable-windows.exe"
nice catch. I have just merged the same fix with #1037 already.

2023-01-17 15:59 UTC, hohwille commented on scripts/src/main/resources/scripts/command/docker
> +      kill -9 $PPID
kill -9 $PPID will kill the parent process what is the shell.
This looks kind of dangerous and hackish. I am not sure if this is the way to go...

2023-01-31 11:32 UTC, Amueller36 commented
https://github.com/devonfw/ide/pull/1045 
I did a pull request regarding this issue

2023-01-31 11:32 UTC, closed without merging