#998: fixed release-info messed with installation output
devonfw/ide pull request #1046
Opened 2023-01-30 16:05 UTC by Amueller36

Added mvn setup call at the beginning of the command as stated by @hohwille. I couldn't reproduce the error so I assume that might be it.

2023-01-30 16:06 UTC, Amueller36 commented
#998 related issue

2023-02-28 17:38 UTC, hohwille requested changes
@Amueller36 Thanks for this PR. Your fix is fine👍 
However, can you revert the change to `maven.config` please?

2023-02-28 17:38 UTC, hohwille commented on .mvn/maven.config
> +-Drevision=2023.01.001
you should not commit changes to this file.

2023-04-11 09:00 UTC, hohwille approved these changes
@Amueller36 thanks for your PR. Workaround should fix the problem though it will install maven also if the release build will not use maven...

2023-04-11 15:36 UTC, merged