#1085 Align tool names in scripts
devonfw/ide pull request #1095
Opened 2023-04-12 15:17 UTC by CREITZ25

#1085 Align tool names in scripts

2023-04-12 15:18 UTC, CREITZ25 commented
@hohwille
In order to adjust the cobigen commandlet according to the specifications, the path cobigen-cli must be changed to cobigen. The variable COBIGEN_CLI_HOME should also be adjusted to COBIGEN_HOME. However, the problem arises that the variable is already used in the cobigen environment. Therefore, in the scripts/devon.properties file, the variable COBIGEN_HOME is already set to a configuration file or directory. How do I have to proceed here?

https://github.com/devonfw/cobigen/blob/master/documentation/cobigen-core_configuration.asciidoc

2023-04-12 15:19 UTC, CREITZ25 commented
@hohwille after the issue has been implemented, the doGetToolFolderName function is free of the exceptions and generates the name of the software from the transferred software path. Perhaps the function should be renamed to doGetToolName, or replace the calls directly with the contents of the function.

2023-04-12 15:19 UTC, CREITZ25 commented
node is already adapted

2023-04-13 07:18 UTC, hohwille commented
> @hohwille after the issue has been implemented, the doGetToolFolderName function is free of the exceptions and generates the name of the software from the transferred software path. Perhaps the function should be renamed to doGetToolName, or replace the calls directly with the contents of the function.

yes, we should remove this function as it is more or less nothing than `basename`.
so you can change things like
```
doListSoftwareVersions "$(doGetToolFolderName "${0}")"
```
to simply
```
doListSoftwareVersions "${0}"
```

Theoretically in some cases also a path could be provided as argument where we would need to do `${0/*\//}` but I can not find any place where the function is used with a path rather than just the tool name itself.

2023-04-24 08:15 UTC, hohwille requested changes
@CREITZ25 thanks for implementing this story. Looks good and you have catched all places to adapt except the very last one I commented. 👍 
IMHO it is fine to leave `MAVEN_HOME` and not rename it to `MVN_HOME` and we already discussed the name clash between `COBIGEN_HOME` so also `COBIGEN_CLI_HOME` must stay.

As we have some dependencies with other stories, those have to be implemented and merged, before we can merge this one as otherwise it will break existing functionality on master and make tests red...

2023-04-24 08:32 UTC, CREITZ25 commented on scripts/src/main/resources/scripts/command/mvn
> +  doInstall "mvn" "${MAVEN_VERSION}" "${1}" "" "${MAVEN_HOME}" "-"
Of course, I forgot it

2023-04-24 08:37 UTC, hohwille approved these changes
@CREITZ25 thanks for lightning fast update. Now ready but waiting for dependent issues to be merged first (see #1085 where I added the dependencies to the comment).

2023-06-02 12:21 UTC, hohwille approved these changes
@CREITZ25 IMHO all is correct here and this could be merged.
Can we align on the different related stories that we all need to merge together to result in a working state as just merging parts of the epic like only this PR may result in a broken state...

2023-06-06 11:06 UTC, merged