#1369: added latest stable version pattern
devonfw/ide pull request #1374
Opened 2024-01-03 14:25 UTC by MattesMrzik

To select the latest stable version, one can pass *! or something like 1.2*!

2024-01-05 09:19 UTC, CREITZ25 commented
@MattesMrzik Looks good, but check variables between line 1914 ans 1930. 
For example "$version" should be written with brackets "${version}", or not?

2024-01-05 14:40 UTC, hohwille requested changes
@MattesMrzik thanks for this great PR. You also cleanup the code removing lots of typos and trailing spaces. Your implementation to get the latest stable version also looks solid and has nice documentation.
As already commented, you are using a tool that is not available on MacOS so you need to adapt that part and find a different solution.
Further you missed a small but important detail from the story demand:
You need to invert the invocations of the functions `getLatestSoftwareVersion` and `getLatestStableSoftwareVersion`.
See from IDEasy:
```
  /** {@link VersionIdentifier} "*" that will resolve to the latest stable version. */
  public static final VersionIdentifier LATEST = VersionIdentifier.of("*");
```

If the version is undefined we also want to install the latest *stable* version, what is the main purpose of the story as devonfw-ide users got unstable versions installed by default if those are the latest ones available.

2024-01-06 00:05 UTC, hohwille commented
setup test failed with:
> ******** ATTENTION ********
Could not resolve version prefix 17* : no matching version found in /home/runner/work/ide/ide/scripts/target/integration-test/test-setup/urls/java/java/
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Command 'java setup silent' failed with exit code 255

2024-01-08 16:03 UTC, MattesMrzik commented on scripts/src/main/resources/scripts/functions
> +    mapfile -t versions < <(find "${DEVON_IDE_HOME}"/urls/"${software}"/"${edition}" -mindepth 1 -maxdepth 1 -print | awk -F'/' '{print $NF}' | sort -rV)
I changed it to make it compatible with macOS

2024-01-08 18:37 UTC, hohwille approved these changes
@MattesMrzik thanks for your fix. Now complete and ready for merge. Good job 👍

2024-01-08 18:39 UTC, merged