added colored output
devonfw/ide pull request #655
Opened 2021-12-21 10:18 UTC by maybeec

warnings are outputted yellow
steps cyan
sucess messages green
error messages red

2021-12-21 15:13 UTC, hohwille requested changes
@maybeec thanks for your PR.
It is a great improvement if we get the coloring.
However as already discussed in #631 the colors lead to strange output and confusion in CMD that also needs to be supported by devonfw-ide on windows.
IMHO we should first get this solved or find a way to determine that case and prevent color escape codes in CMD.
Besides you created several bugs that I commented.
As I am short on time, I would pick up this issue next year and create a new release with this great feature in January 2022 unless you have to time to get everything solves yourself immediately...

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/command/ide
> +    doEcho -e "\e[96m\n*** Setting up ${tool} ***\e[39m"
Did you do search&replace of `echo` case insensitive?
`-e` is wrong here for `doEcho`.
See here: 
https://github.com/devonfw/ide/blob/d462bc6ae93075f613081d710cd88f1490fd1ed8/scripts/src/main/resources/scripts/functions#L149

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/command/ide
> +    doEcho -e "\e[92mSuccess\e[39m"
same here

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/command/ide
> +        doEcho -e "\e[96m\n*** Setting up ${software} ***\e[39m"
same here

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/command/ide
> +    doEcho -e "\e[96m\n*** Setting up ${tool} ***\e[39m"
Please note there is also `doWarning` and `doDebug`, etc.
We could add the color automatically for `doWarning` what would make much more sense then hardcoding this strange escape syntax redundantly everywhere...

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/devon
> +    echo -e "\e[93mYou are not inside a devonfw-ide installation: ${L_PWD}\e[39m"
maybe use `doWarning`?

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/devon
> +    echo -e "\e[91mERROR: DEVON_IDE_HOME does not exist!\e[39m"
we should use `doWarning` or add `doError`

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/devon
> +    echo -e "\e[93mUnknown command ${command}\e[39m"
use `doWarning` instead.

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +  echo -e "\e[91mWe are sorry for the inconvenience. Please check the above errors, resolve them and try again.\e[39m"
we could simplify by joining both to a single echo with `\n` separator.

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +      doEcho -e "\e[93mCommand ${1} is not executable. Trying to repair...\e[39m"
use `doWarning`

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +      doEcho -e "\e[91mERROR: command '${command_name} ${*}' failed with exit code ${result}\e[39m"
same here

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +    doEcho -e "\e[91mFailed to download ${url} with exit code ${result}\e[39m"
same here

2021-12-21 15:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +    doDebug -e "\e[32mDownload of ${DOWNLOAD_FILENAME} from ${url} succeeded.\e[39m"
same here

2021-12-22 06:12 UTC, maybeec commented
@hohwille at least in my tests I could not see any strange output.
I will have a look at the ticket you mentioned but I think it's an issue of the Java generated console output.

@jan-vcapgemini possibly you can give a try and check whether you get strange output on cmd

2022-01-13 18:18 UTC, maybeec commented
Any news on that? I feel it's ready to be tested. I couldnt made some more Bugfixing but would like to get other opinions as well. Testing welcome

2022-01-26 18:15 UTC, maybeec commented
@hohwille merge conflicts start to raise as the PRs are quite long open. Is there anything I can do in addition you would like to get changed?

2022-06-07 08:04 UTC, hohwille commented
I tested `devon mvn install` in CMD shell and it gives color output just as with calling `mvn install` directly.
So it is definitely not a problem or bug of a `bash` being in between CMD and the outputting process.
I can take over the conflict resolution here and retest the latest code.
If all works out, I can merge this.
Thanks for all your work and great that I can be back after being M.I.A.

2022-06-07 11:12 UTC, hohwille commented
@maybeec thanks for your great work. 👍 
It works fine beside some small bugs and things to improve that I will take over.
Replacing this PR with PR #778

2022-06-07 11:12 UTC, closed without merging