introduced mcurl for parallel connections
devonfw/ide pull request #661
Opened 2021-12-21 19:26 UTC by maybeec

Tested on windows git bash with success

2021-12-22 08:05 UTC, maybeec commented
needs some more testing - had some issues with some of the software.

2021-12-22 12:13 UTC, hohwille requested changes
This PR introduces build errors. Besides some shellcheck peanuts, I am deeply concerned about this one:
```
*** Setting up mvn ***
Starting installation of java in version 11.0.13_8 to /home/runner/work/ide/ide/scripts/target/integration-test/test-setup/software/java
Trying to download java-11.0.13_8-linux.tar.gz from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz
Download https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz to /tmp/java-11.0.13_8.QfXnH4 with 2 tasks.


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to run command: tar xf '/home/runner/Downloads/devonfw-ide/java-11.0.13_8-linux.tar.gz' -C '/home/runner/work/ide/ide/scripts/target/integration-test/test-setup/updates/extracted/java'

******** ATTENTION ********
ERROR: Failed to run command tar
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 2
```

So this download works quite reliable without mcurl but now broke. This says me that we will introduce more problems with mcurl than we solve. So without any further investigation or improvements I vote against going for mcurl now.

2021-12-22 12:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> -  curl ${curl_opt} -fL "${url}" -o "${tmp_file}"
you removed quiet/silent support without a replacement.

2021-12-22 12:13 UTC, hohwille commented on scripts/src/main/resources/scripts/functions
> +  bash $SCRIPT_DIR/mcurl -o "${tmp_file}" "${url}"
avoid exposing additional variables (see e.g. #5) and instead use `local` variables.
Further, IMHO the way you determine the script dir is not 100% reliable. Simply use `${DEVON_IDE_HOME}/scripts` instead what will work in all cases.

2022-08-29 17:45 UTC, hohwille commented
How should we proceed here?
Are there benchmarks proving that mcurl will bring a huge benefit to speed our downloads and will there be someone available solving the problems and ensuring that mcurl downloads are reliable?
Or should we close this PR and issue #703?

2022-09-23 11:37 UTC, maybeec commented
I would like to keep it like a draft and have some additional look at it once I find back some time if you are ok. Otherwise close it and I can reopen it at any point in time

2023-01-20 13:48 UTC, hohwille commented
For house-keeping I will close this PR. Feel free to reopen at any time when there is any progress.

2023-01-20 13:48 UTC, closed without merging