#849: Integration of gcviewer
devonfw/ide pull request #862
Opened 2022-08-30 11:47 UTC by ahmedagdmoun

Implements #849

2022-08-30 13:00 UTC, ahmedagdmoun commented
I also made a PR for gcviewer mirrors https://github.com/devonfw/ide-mirrors/pull/29

2022-09-02 14:12 UTC, hohwille requested changes
@ahmedagdmoun thanks for integration of gcviewer with this PR. 👍 
I left several review comments for improvement. Can you check and rework accordingly?

2022-09-02 14:12 UTC, hohwille commented on documentation/gcviewer.asciidoc
> +The arguments (`devon oc «args»`) are explained in the following table:
should be `gcviewer` instead of `oc`. Seems you copy & pasted this from openshift CLI :)

2022-09-02 14:12 UTC, hohwille commented on documentation/ide.asciidoc
> +However, it will not remove your current installations (or shared link:software.asciidoc[software] folder). So after running this `uninstall`, simply remove your `DEVON_IDE_HOME` directory of all `de
I can not see any reasonable change here. Do you have your EOL-Style configured properly for git or how can we avoid such phantom changes that spam the diffs?

2022-09-02 14:12 UTC, hohwille commented on documentation/scripts.asciidoc
> +Finally the `devon.properties` file contains defaults for the general link:configuration.asciidoc[configuration] of `devonfw-ide`.
again no change here...

2022-09-02 14:12 UTC, hohwille commented on documentation/scripts.asciidoc
> +Finally the `devon.properties` file contains defaults for the general link:configuration.asciidoc[configuration] of `devonfw-ide`.
However, gcviewer.asciidoc is missing here and should be added.

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/scripts/command/gcviewer
> +  if [ -z "${GCVIEWER_VERSION}" ]
silent option should be supported by all commandlets.
Can you check any other commandlet and incorporate these changes here?

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/scripts/command/gcviewer
> +  doSetup
provide "${2}" as arg (or `shift` and provide `"${*}"` as arg) to support silent setup.

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/scripts/command/gcviewer
> +  doError "Unkown command. Call devon gcviewer to setup or start GCViewer OR devon gcviewer help for available commands"
The hint "Call devon gcviewer to setup or start GCViewer OR devon gcviewer help for available commands" does not really make sense here as still arguments of gcviewer will not be passed to gcviewer and therefore still produce the same error message.
Either remove or turn gcviewer commandlet into a [wrapper](https://github.com/devonfw/ide/blob/d0165928fac059cced751473ddb55a82e2679874/documentation/cli.asciidoc#command-wrapper).

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/scripts/command/ide
> +doSuccess "Completed ${*}"
no need to change `ide` commandlet in this PR. Same problem as above phantom commits.

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/setup.bat
> +popd
another phantom change.

2022-09-02 14:12 UTC, hohwille commented on scripts/src/main/resources/system/windows/windows-terminal/devon-wt-gitbash-uninstall.reg
> +[-HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell\devon_wt_ps\command]
this change does not make any sense to me and is not related to gcviewer.

2022-09-06 10:04 UTC, ahmedagdmoun commented
@hohwille Thank you for your review. I updated the code according to the requested changes and I hope it's ok now. 
Sorry for the many phantom changes. They were mainly caused while resolving merge conflicts. I will try to pay more attention in the future.

2022-09-09 08:58 UTC, hohwille approved these changes
@ahmedagdmoun I added several commits to still get rid of undesired or unrelated changes.
Now everything looks fine. Thanks also for your rework that addressed all my review comments 👍

2022-09-09 09:37 UTC, hohwille commented on scripts/src/main/resources/scripts/command/gcviewer
> +  else
See other commandlets. Your code is not starting `gcviewer` if it is not already installed. That is confusing and different to other commandlets. I will quickly fix it so we can merge this.

2022-09-09 09:41 UTC, hohwille commented on scripts/src/main/resources/scripts/command/gcviewer
> +  else
Done.

2022-09-09 09:42 UTC, hohwille commented
I also tested this and found some last aspects to improve.
Besides #848 all is working perfect, so I will merge.

2022-09-09 10:19 UTC, merged